version: '3.7'
services:
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "8080:80"
      - "81:81"
      - "444:443"
    volumes:
      - "./nginx/data:/data"
      - "./nginx/letsencrypt:/etc/letsencrypt"
    restart: "always"
    depends_on:
      - cache-engine
      - search-engine
      - redis-commander
      - kibana
      - api
    networks:
      reverse-proxy:
        aliases:
          - nginx-proxy-manager
      aaa-network:
  cache-engine:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./cache-engine/data:/data"
      - "./cache-engine/config:/etc/redis"
    environment:
      - APPENDONLY=yes
    networks:
      cache-engine:
        aliases:
          - cache-engine
      aaa-network:
  search-engine:
    image: elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=cluster1-node1
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      search-engine:
        aliases:
          - search-engine
      aaa-network:
        aliases:
          - search-engine
    restart: always
  api:
    image: python:3.7
    environment:
      - FLASK_APP=api.py
    ports:
      - "5000:5000"
    volumes:
      - pip37:/usr/local/lib/python3.7/site-packages
      - "./api:/app"
    command: pip install -r requirements.txt & "python /app/app.py"
    depends_on:
      - search-engine
      - cache-engine
    networks:
      api:
        aliases:
          - api
      aaa-network:
        aliases:
          - api
    restart: always
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./web:/usr/share/nginx/data"
      - "./ssl/certs:/etc/nginx/ssl/certs"
    environment:
      - "HTTPS=true"
    networks:
      web:
        aliases:
          - web
          - aaa-network
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=cache-engine:6379
    restart: always
    networks:
      - aaa-network
  kibana:
    image: kibana:8.6.0
    container_name: kibana
    environment:
     ELASTICSEARCH_HOSTS: http://elasticsearch:9200
     SERVER_HOSTS: 0.0.0.0
    ports:
      - "5601:5601"
    restart: always
    depends_on:
      - search-engine
    networks:
      search-engine:
        aliases:
          - kibana
      aaa-network:
        aliases:
          - kibana
volumes:
  pip37:
networks:
    reverse-proxy:
    cache-engine:
    search-engine:
    api:
    aaa-network: