version: '3.7'
services:
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "8080:80"
      - "81:81"
      - "444:443"
    volumes:
      - "./nginx/data:/data"
      - "./nginx/letsencrypt:/etc/letsencrypt"
    restart: "always"
    depends_on:
      - cache-engine
      - search-engine
      - redis-commander
      - kibana
      - api
    networks:
      reverse-proxy:
        aliases:
          - nginx-proxy-manager
      aaa-network:
  cache-engine:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./cache-engine/data:/data"
      - "./cache-engine/config:/etc/redis"
    environment:
      - APPENDONLY=yes
    networks:
      cache-engine:
        aliases:
          - cache-engine
      aaa-network:
  search-engine:
    image: elasticsearch/elasticsearch:.17.8
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./search-engine/data:/usr/share/elasticsearch/data"
      - "./search-engine/config:/usr/share/elasticsearch/config"
      - "./search-engine/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      search-engine:
        aliases:
          - search-engine
      aaa-network:
        aliases:
          - search-engine
    restart: always
  api:
    image: python:3.7
    environment:
      - FLASK_APP=api.py
    ports:
      - "5000:5000"
    volumes:
      - "./api:/app"
    command: "python /app/app.py"
    depends_on:
      - search-engine
      - cache-engine
    networks:
      api:
        aliases:
          - api
      aaa-network:
        aliases:
          - api
    restart: always
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./web:/usr/share/nginx/data"
      - "./ssl/certs:/etc/nginx/ssl/certs"
    environment:
      - "HTTPS=true"
    networks:
      web:
        aliases:
          - web
          - aaa-network
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=cache-engine:6379
    restart: always
    networks:
      - aaa-network
  kibana:
    image: kibana/kibana:7.17.8
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://search-engine:9200
    restart: always
    networks:
      - aaa-network

networks:
    reverse-proxy:
    cache-engine:
    search-engine:
    api:
    aaa-network: